"""add job table

Revision ID: 5cc5d1686947
Revises: a341de379a02
Create Date: 2026-06-04 21:25:59.135618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cc5d1686947"
down_revision: Union[str, Sequence[str], None] = "a341de379a02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("technician_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planifié", "en_cours", "terminé", "annulé", name="jobstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("basse", "normale", "haute", "urgente", name="priority"),
            nullable=False,
        ),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_start_time", sa.Time(), nullable=True),
        sa.Column("scheduled_end_time", sa.Time(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_client_id"), "job", ["client_id"], unique=False)
    op.create_index(op.f("ix_job_id"), "job", ["id"], unique=False)
    op.create_index(op.f("ix_job_priority"), "job", ["priority"], unique=False)
    op.create_index(
        op.f("ix_job_scheduled_date"), "job", ["scheduled_date"], unique=False
    )
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_index(
        op.f("ix_job_technician_id"), "job", ["technician_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_technician_id"), table_name="job")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_scheduled_date"), table_name="job")
    op.drop_index(op.f("ix_job_priority"), table_name="job")
    op.drop_index(op.f("ix_job_id"), table_name="job")
    op.drop_index(op.f("ix_job_client_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
